#!/usr/bin/env node

var wrup = require("wrapup")(),
    fs     = require("fs"),
    json   = require("./package")

console.warn("")
console.warn("              .- " + json.version)
console.warn("  .-.-..-..-.-|-._.")
console.warn("  ' ' '`-'`-' ' ' '\n")

var header = "/*\n\
---\n\
provides: moofx\n\
version: " + json.version + "\n\
description: A CSS3-enabled javascript animation library\n\
homepage: http://moofx.it\n\
author: Valerio Proietti <@kamicane> (http://mad4milk.net)\n\
license: MIT (http://mootools.net/license.txt)\n\
includes: cubic-bezier by Arian Stolwijk (https://github.com/arian/cubic-bezier)\n\
...\n\
*/\n\n"

var args = process.argv.slice(2)

var wrupit = function(){

    wrup.options({output: "./moofx.js", watch: args.indexOf("--watch") > -1, compress: true})

    wrup.require("moofx", "./")

    wrup.on("end", function(js){
        var contents = fs.readFileSync("./moofx.js")
        contents = header + contents;
        fs.writeFileSync("./moofx.js", contents, "utf-8")
        console.log("  written ./moofx.js\n")
    })

    wrup.up()
}

wrupit()
