#!/usr/bin/env node

var WrapUp = require("wrapup"),
    fs     = require("fs"),
    json   = require("./package")

console.warn("")
console.warn("              .- " + json.version)
console.warn("  .-.-..-..-.-|-._.")
console.warn("  ' ' '`-'`-' ' ' '\n")

var header = "/*\n\
---\n\
provides: moofx\n\
version: " + json.version + "\n\
description: A CSS3-enabled javascript animation library\n\
homepage: http://moofx.it\n\
author: Valerio Proietti <@kamicane> (http://mad4milk.net)\n\
license: MIT (http://mootools.net/license.txt)\n\
includes: cubic-bezier by Arian Stolwijk (https://github.com/arian/cubic-bezier)\n\
...\n\
*/\n\n"

var args = process.argv.slice(2)

var wrupit = function(){
    var wrup = WrapUp()
    wrup.log("  ERROR: ")

    wrup.exclude("array.isArray", "array.every", "array.some", "array.filter",
                 "string.contains", "string.number", "string.escape", "string.decode",
                 "fixEnumBug")

    if (args.indexOf("--css3") > -1) wrup.exclude("css3")

    wrup.require("moofx", "./")

    wrup.on("done", function(js){
        fs.writeFileSync("./moofx.js", header + js.replace("%version%", json.version), "utf-8")
        console.log("  written moofx.js\n")
    })

    wrup.up({watch: args.indexOf("--watch") > -1})
}

wrupit()
