#!/usr/bin/env node

var wrup = require("wrapup")
var fs = require("fs")
var json = require("./package")

console.warn("")
console.warn("              .- " + json.version)
console.warn("  .-.-..-..-.-|-._.")
console.warn("  ' ' '`-'`-' ' ' '\n")

var header = "/*\n\
---\n\
provides: moofx\n\
version: " + json.version + "\n\
description: A CSS3-enabled javascript animation library on caffeine\n\
homepage: http://moofx.it\n\
author: Valerio Proietti <@kamicane> (http://mad4milk.net)\n\
license: MIT (http://mootools.net/license.txt)\n\
includes: cubic-bezier by Arian Stolwijk (https://github.com/arian/cubic-bezier)\n\
...\n\
*/\n\n"

var wrupit = function(){
	var pkg = wrup().package()
	fs.writeFileSync("./moofx.js", header + pkg.up(), "utf-8")
	fs.writeFileSync("./moofx-min.js", header + pkg.up({compress: true}), "utf-8")
	console.log("  written moofx.js / moofx-min.js\n")
}

wrupit()

var a2 = process.argv[2]

if (a2 == '--watch' || a2 == '-w'){

	console.log("  watching...\n")

	var scripts = ['./lib/index.js', './lib/color.js', './lib/frame.js']

	scripts.forEach(function(script){
		var filedata = fs.readFileSync(script, "utf-8")

		fs.watchFile(script, {interval: 10}, function(){
			var data = fs.readFileSync(script, "utf-8")
			if (filedata !== data){
				wrupit()
				filedata = data
			}
		})

	})

}
