/*
---
provides: moofx
version: 3.0.0-16-y
description: A CSS3-enabled javascript animation library on caffeine
website: http://moofx.it
author: Valerio Proietti <@kamicane> (http://mad4milk.net)
license: MIT (http://mootools.net/license.txt)
...
*/
(function(){var p,ia,i,w,X,I,E,R,F,Y,J,S,x,Z,ja,ka,T,la,ma,K,v,na,$,aa,A,L,ba,y,oa,pa,M,r,qa,N,z,s,G,ca,ra,U,da,k,ea,q,o,h,fa,sa,O,V,W,H,C,D,P,n,m,l,u,Q,ta,ga,ua=Object.prototype.hasOwnProperty,t=function(a,b){function c(){this.constructor=a}for(var d in b)ua.call(b,d)&&(a[d]=b[d]);c.prototype=b.prototype;a.prototype=new c;a.__super__=b.prototype;return a};ea=function(a){this.valueOf=function(){return a};return this};k=function(a){return a?new ea(null!=a.length?a:1===a.nodeType?[a]:[]):null};k.prototype=
ea.prototype;pa={maroon:"#800000",red:"#ff0000",orange:"#ffA500",yellow:"#ffff00",olive:"#808000",purple:"#800080",fuchsia:"#ff00ff",white:"#ffffff",lime:"#00ff00",green:"#008000",navy:"#000080",blue:"#0000ff",aqua:"#00ffff",teal:"#008080",black:"#000000",silver:"#c0c0c0",gray:"#808080"};ma=function(a,b,c,d){null==d&&(d=1);a=parseInt(a,10);b=parseInt(b,10);c=parseInt(c,10);d=parseFloat(d);return!(255>=a&&0<=a)||!(255>=b&&0<=b)||!(255>=c&&0<=c)||!(1>=d&&0<=d)?null:[Math.round(a),Math.round(b),Math.round(c),
d]};ja=function(a){var b,c,d;3===a.length&&(a+="f");4===a.length&&(b=a.charAt(0),c=a.charAt(1),d=a.charAt(2),a=a.charAt(3),a=b+b+c+c+d+d+a+a);6===a.length&&(a+="ff");d=[];for(b=0,c=a.length;b<=c;b+=2)d.push(parseInt(a.substr(b,2),16)/(6===b?255:1));return d};T=function(a,b,c){0>c&&(c+=1);1<c&&(c-=1);return c<1/6?a+6*(b-a)*c:0.5>c?b:c<2/3?a+6*(b-a)*(2/3-c):a};ka=function(a,b,c,d){var e,f;null==d&&(d=1);a/=360;b/=100;c/=100;d/=1;if(1<a||0>a||1<b||0>b||1<c||0>c||1<d||0>d)return null;0===b?f=a=c:(b=0.5>
c?c*(1+b):c+b-c*b,e=2*c-b,f=T(e,b,a+1/3),c=T(e,b,a),a=T(e,b,a-1/3));return[255*f,255*c,255*a,d]};k.color=function(a,b){var c;if("string"!==typeof a)return null;a=pa[a=a.replace(/\s+/g,"")]||a;if(a.match(/^#[a-f0-9]{3,8}/))a=ja(a.replace("#",""));else if(c=a.match(/([\d.])+/g))if(a.match(/^rgb/))a=c;else if(a.match(/^hsl/))a=ka.apply(null,c);else return null;else return null;if(!a||!(a=ma.apply(null,a)))return null;if(b)return a;1===a[3]&&a.splice(3,1);return"rgb"+(3<a.length?"a":"")+"("+a+")"};A=
[];V=!1;ra=function(a){var b;null==a&&(a=+new Date);V=!1;for(b=A.length;b;)A.splice(--b,1)[0](a);return null};sa=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){return setTimeout(a,1E3/60)};k.requestFrame=function(a){A.push(a);V||(V=!0,sa(ra));return this};k.cancelFrame=function(a){var b,c,d;for(c=0,d=A.length;c<d;c++)b=A[c],b===a&&A.splice(c,1);return this};ba=k.cancelFrame;
O=k.requestFrame;oa=k.color;C=String;o=parseFloat;L=function(a){return a.replace(/-\D/g,function(a){return a.charAt(1).toUpperCase()})};ca=function(a){return a.replace(/[A-Z]/g,function(a){return"-"+a.charAt(0).toLowerCase()})};y=function(a){return C(a).replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")};M="undefined"!==typeof getComputedStyle?function(a){var b;b=getComputedStyle(a);return function(c){return b?b.getPropertyValue(ca(c)):""}}:function(a){var b;b=a.currentStyle;return function(c){return b?
b[L(c)]:""}};h={};s={};H={};G=document.documentElement;aa={};z=function(a){return s[a]||(s[a]=function(){var b;b=h[a]||Y;return function(){return(new b(M(this)(a))).toString(!0,this)}}())};W=function(a){return H[a]||(H[a]=function(){var b;b=h[a]||Y;return function(c){return this.style[a]=(new b(c)).toString()}}())};P=document.createElement("div");fa=function(a,b){var c,d;c=a.parentNode;d=1;c&&(P.style.cssText="border:none;margin:none;padding:none;visibility:hidden;position:absolute;height:0;"+("width:100"+
b+";"),c.appendChild(P),d=P.offsetWidth/100,c.removeChild(P));return d};p=function(){function a(){}a.prototype.extract=function(){return[this]};a.prototype.toString=function(){return C(this.value)};return a}();Y=function(a){function b(c){null==c&&(c="");this.value=C(c)}t(b,a);return b}(p);F=function(a){function b(c){var a;null==c&&(c="");this.value=isFinite(a=o(c))?a:c}t(b,a);return b}(p);i=function(){function a(){}a.prototype.extract=function(){return this.parsed};a.prototype.toString=function(a,
c){var d,e=y,f,g,j,ha;j=this.parsed;ha=[];for(f=0,g=j.length;f<g;f++)d=j[f],ha.push(d.toString(a,c));return e(ha.join(" "))};return a}();E=function(a){function b(c){null==c&&(c="");"auto"===c?this.value="auto":(c=y(C(c)).match(/^([-\d.]+)(%|cm|mm|in|px|pt|pc|em|ex|ch|rem|vw|vh|vm)?$/))?(this.value=o(c[1]),this.unit=0===this.value||!c[2]?"px":c[2]):this.value=""}t(b,a);b.prototype.toString=function(c,a){return"auto"===this.value?this.value:c&&""===this.value?"0px":""===this.value?"":a&&"px"!==this.unit?
""+fa(a,this.unit)*this.value+"px":this.value+this.unit};return b}(p);I=function(a){function b(c){"transparent"===c&&(c="#00000000");this.value=c?oa(c,!0):""}t(b,a);b.prototype.toString=function(c){return c&&!this.value?"rgba(0,0,0,1)":!this.value?"":!c&&("transparent"===this.value||0===this.value[3])?"transparent":c||1!==this.value[3]?"rgba("+this.value+")":"rgb("+this.value[0]+","+this.value[1]+","+this.value[2]+")"};return b}(p);da=function(a){var b;b=a.length;1===b?a.push(a[0],a[0],a[0]):2===
b?a.push(a[0],a[1]):3===b&&a.push(a[1]);return a};R=function(a){function b(c){var a,b;null==c&&(c="");b=da(y(c).split(" "));var f,g;g=[];for(c=0,f=b.length;c<f;c++)a=b[c],g.push(new E(a));this.parsed=g}t(b,a);return b}(i);X=function(a){function b(c){null==c&&(c="");this.value=(c=y(c)).match(/none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|inherit/)?c:""}t(b,a);b.prototype.toString=function(c){return c&&!this.value?"none":this.value};return b}(p);w=function(a){function b(c){var a,
b,f;null==c&&(c="");"none"===c&&(c="0 none #000");c=y(c).match(/((?:[\d.]+)(?:[\w%]+)?)\s(\w+)\s(rgb(?:a)?\([\d,\s]+\)|hsl(?:a)?\([\d,\s]+\)|#[a-f0-9]+|\w+)/)||[];this.parsed=[new E(null!=(a=c[1])?a:""),new X(null!=(b=c[2])?b:""),new I(null!=(f=c[3])?f:"")]}t(b,a);return b}(i);i=function(a){function b(c){var a;null==c&&(c="");var c=da(c.match(/rgb(a)?\([\d,\s]+\)|hsl(a)?\([\d,\s]+\)|#[a-f0-9]+|\w+/g)||[""]),b,f,g;g=[];for(b=0,f=c.length;b<f;b++)a=c[b],g.push(new I(a));this.parsed=g}t(b,a);return b}(i);
m=["Top","Right","Bottom","Left"];n=["TopLeft","TopRight","BottomRight","BottomLeft"];h.color=h.backgroundColor=I;h.width=h.height=h.fontSize=h.backgroundSize=E;for(l=0,Q=m.length;l<Q;l++){r=m[l];v="border"+r;ga=["margin"+r,"padding"+r,v+"Width",r.toLowerCase()];for(u=0,ta=ga.length;u<ta;u++)q=ga[u],h[q]=E;h[v+"Color"]=I;h[v+"Style"]=X;h[v]=w;s[v]=function(){return[z(v+"Width").call(this),z(v+"Style").call(this),z(v+"Color").call(this)].join(" ")}}for(l=0,u=n.length;l<u;l++)r=n[l],h["border"+r+"Radius"]=
E;h.zIndex=function(a){function b(c){this.value="auto"===c?c:o(c)}t(b,a);return b}(p);Q=["margin","padding"];n=function(a){h[a]=R;return s[a]=function(){var b,c,d,e;e=[];for(d=0,c=m.length;d<c;d++)b=m[d],e.push(z(a+b).call(this));return e.join(" ")}};for(l=0,u=Q.length;l<u;l++)q=Q[l],n(q);h.borderRadius=R;s.borderRadius=function(){var a,b,c,d;d=[];for(c=0,b=m.length;c<b;c++)a=m[c],d.push(z("border"+a+"Radius").call(this));return d.join(" ")};h.borderWidth=R;h.borderColor=i;u=["Width","Style","Color"];
i=function(a){return s["border"+a]=function(){var b,c,d,e;e=[];for(d=0,c=m.length;d<c;d++)b=m[d],e.push(z("border"+b+a).call(this));return e.join(" ")}};for(l=0,n=u.length;l<n;l++)D=u[l],i(D);h.border=w;s.border=function(){var a,b,c,d;for(d=0,c=m.length;d<c;d++){a=m[d];a=z(v="border"+a).call(this);if(b&&a!==b)return null;b=a}return a};N=null!=G.style.MsFilter?"MsFilter":null!=G.style.filter?"filter":null;h.opacity=F;null==G.style.opacity&&N&&(U=/alpha\(opacity=([\d.]+)\)/i,H.opacity=function(a){var b,
a=(a=1===o(a))?"":"alpha(opacity="+100*a+")";b=M(this)(N);return this.style[N]=U.test(b)?b.replace(U,a):b+a},s.opacity=function(){var a;return C(!(a=M(this)(N).match(U))?1:a[1]/100)});n=["MozTransform","WebkitTransform","OTransform","msTransform","transform"];for(i=0,F=n.length;i<F;i++)if(w=n[i],null!=G.style[w]){J=w;break}h.transform=S=function(a){function b(c){var a,b,f,g,j;a={translate:"0px,0px",rotate:"0deg",scale:"1,1",skew:"0deg,0deg"};if(c=y(c).match(/\w+\s?\([-,.\w\s]+\)/g)){f=function(c){var b,
e,f,g;if(c=c.replace(/\s+/g,"").match(/^(translate|scale|rotate|skew)\((.*)\)$/))switch(q=c[1],b=c[2].split(","),q){case "translate":if(2>b.length)break;g=[];for(f=0,e=b.length;f<e;f++)c=b[f],g.push(a[q]=o(c)+"px");return g;case "rotate":return a[q]=o(b[0])+"deg";case "scale":1===b.length&&(b=[b[0],b[0]]);g=[];for(f=0,e=b.length;f<e;f++)c=b[f],g.push(a[q]=o(c));return g;case "skew":if(1===b.length)break;g=[];for(f=0,e=b.length;f<e;f++)c=b[f],g.push(a[q]=o(c)+"deg");return g}};for(j=0,g=c.length;j<
g;j++)b=c[j],f(b)}this.transforms=a}t(b,a);b.prototype.toString=function(){var c,a,b,f,g;f=["translate","rotate","scale","skew"];g=[];for(b=0,a=f.length;b<a;b++)c=f[b],g.push(""+c+"("+this.transforms[c]+")");return g.join(" ")};return b}(p);J?(aa.transform=J,H.transform=function(a){return this.style[J]=(new S(a)).toString()},s.transform=function(){return(new S(this.style[J])).toString()}):(H.transform=function(){},s.transform=function(){return(new S).toString()});$={};na=function(a,b,c,d,e,f){var g,
j,h,i,B,l,k,n;k=[0];n=[0];l=0;for(i=1;i<e-1;)B=1/e*i,g=3*Math.pow(1-B,2)*B,j=3*Math.pow(B,2)*(1-B),h=Math.pow(B,3),B=a*g+c*j+h,g=b*g+d*j+h,B-l>f&&(l=B,k.push(B),n.push(g)),i++;k.push(1);n.push(1);return function(c){var a,b,d;a=0;for(d=k.length-1;a<=d&&!(b=Math.floor((a+d)/2),k[b]===c);)k[b]>c?d=b-1:a=b+1;return n[b]}};qa={"default":"cubic-bezier(0.25, 0.1, 0.25, 1.0)",linear:"cubic-bezier(0, 0, 1, 1)","ease-in":"cubic-bezier(0.42, 0, 1.0, 1.0)","ease-out":"cubic-bezier(0, 0, 0.58, 1.0)","ease-in-out":"cubic-bezier(0.42, 0, 0.58, 1.0)"};
p=function(){function a(a,c){this.node=a;this.property=c;this.setter=W(c);this.getter=z(c)}a.prototype.start=function(a,c){var d;this.stop();d=!0;a===c&&(d=!1);0===this.duration&&(this.setter.call(this.node,c),d=!1);d||O(this.callback);return d};a.prototype.setOptions=function(a){var c;null==a&&(a={});if(!(this.duration=this.parseDuration(null!=(c=a.duration)?c:"500ms")))throw Error(""+a.duration+" is not a valid duration");if(!(this.equation=this.parseEquation(a.equation||"default")))throw Error(""+
a.equation+" is not a valid equation");this.callback=a.callback||function(){};return this};a.prototype.parseDuration=function(a){var c;if(c=C(a).match(/([\d.]+)(s|ms)/)){a=o(c[1]);c=c[2];if("s"===c)return 1E3*a;if("ms"===c)return a}else return null};a.prototype.parseEquation=function(a){var c,d,e,f,a=qa[a]||a;if(a=a.replace(/\s+/g,"").match(/^cubic-bezier\(([\d.]+),([\d.]+),([\d.]+),([\d.]+)\)$/)){e=a.slice(1);f=[];for(d=0,c=e.length;d<c;d++)a=e[d],f.push(o(a));return f}return null};return a}();la=
function(a){function b(a,d){var e=this;b.__super__.constructor.call(this,a,d);this.bstep=function(a){return e.step(a)}}t(b,a);b.prototype.start=function(a,d){if(b.__super__.start.call(this,a,d)){this.time=0;a=this.numbers(a);d=this.numbers(d);if(a[0].length!==d[0].length)throw Error("property length mismatch");this.from=a[0];this.to=d[0];this.template=d[1];O(this.bstep)}return this};b.prototype.stop=function(){ba(this.bstep);return this};b.prototype.step=function(a){var b,e,f,g,j,h;this.time||(this.time=
a);e=(a-this.time)/this.duration;1<e&&(e=1);a=this.equation(e);g=this.template;h=this.from;for(f=0,j=h.length;f<j;f++)b=h[f],D=this.to[f],g=g.replace("@",D!==b?this.compute(b,D,a):D);this.setter.call(this.node,g);1!==e?O(this.bstep):this.callback(D);return this};b.prototype.parseEquation=function(a){var d,e,a=b.__super__.parseEquation.call(this,a);e=a.toString();d=""+e+":"+this.duration+"ms";return e===[0,0,1,1].toString()?function(a){return a}:$[d]||($[d]=na(a[0],a[1],a[2],a[3],2*this.duration,1E3/
60/this.duration/4))};b.prototype.compute=function(a,b,e){return(b-a)*e+a};b.prototype.numbers=function(a){var b;b=[];a=a.replace(/[-\d.]+/g,function(a){b.push(o(a));return"@"});return[b,a]};return b}(p);n=["WebkitTransition","MozTransition","transition"];for(i=0,F=n.length;i<F;i++)if(w=n[i],null!=G.style[w]){x=w;break}Z="MozTransition"===x?"transitionend":"webkitTransitionEnd";ia=function(a){function b(a,d){var e=this;b.__super__.constructor.call(this,a,d);this.hproperty=ca(aa[this.property]||this.property);
this.bdefer=function(a){return e.defer(a)};this.bcomplete=function(a){return e.complete(a)}}t(b,a);b.prototype.start=function(a,d){b.__super__.start.call(this,a,d)&&(this.to=d,O(this.bdefer));return this};b.prototype.stop=function(a){this.running?(this.running=!1,a&&this.setter.call(this.node,this.getter.call(this.node)),this.clean()):ba(this.bdefer);return this};b.prototype.defer=function(){this.running=!0;this.modCSS(!0);this.node.addEventListener(Z,this.bcomplete,!1);this.setter.call(this.node,
this.to);return null};b.prototype.clean=function(){this.modCSS();this.node.removeEventListener(Z,this.bcomplete);return null};b.prototype.complete=function(a){a&&a.propertyName===this.hproperty&&(this.running=!1,this.clean(),this.callback());return null};b.prototype.removeProp=function(a,b,e,f){var g,j,h,i;for(g=0,i=b.length;g<i;g++)if(h=b[g],h===a){j=g;break}null!=j&&(b.splice(j,1),e.splice(j,1),f.splice(j,1));return null};b.prototype.modCSS=function(a){var b,e;b=M(this.node);e=b(x+"Property").replace(/\s+/g,
"").split(",");r=b(x+"Duration").replace(/\s+/g,"").split(",");b=b(x+"TimingFunction").replace(/\s+/g,"").match(/cubic-bezier\(([\d.,]+)\)/g);this.removeProp("all",e,r,b);this.removeProp(this.hproperty,e,r,b);a&&(e.push(this.hproperty),r.push(this.duration),b.push(this.equation));this.node.style[x+"Property"]=e;this.node.style[x+"Duration"]=r;this.node.style[x+"TimingFunction"]=b;return null};b.prototype.parseDuration=function(a){return""+b.__super__.parseDuration.call(this,a)+"ms"};b.prototype.parseEquation=
function(a){return"cubic-bezier("+b.__super__.parseEquation.call(this,a)+")"};return b}(p);K=new (function(){function a(){this.uid=0;this.animations={}}a.prototype.retrieve=function(a,c){var d,e,f;d=null!=(f=a["\u00b5id"])?f:a["\u00b5id"]=(this.uid++).toString(36);d=(e=this.animations)[d]||(e[d]={});return d[c]||(d[c]=x?new ia(a,c):new la(a,c))};a.prototype.starts=function(a,c,d){var e,f,g,j,i,k,l,n,r,o,t,p,s,m,u,v,q,w,x,A,y;null==d&&(d={});k=typeof d;d="function"===k?{callback:d}:"string"===k?{duration:d}:
d;e=d.callback||function(){};r=f=0;d.callback=function(){if(++f===r)return e()};for(m in c){w=c[m];m=L(m);s=h[m];if(!s)throw Error("no parser for "+m);u=W(m);k=z(m);for(y=0,x=a.length;y<x;y++){o=a[y];r++;n=this.retrieve(o,m);t=new s(k.call(o));p=new s(w);i=t.extract();v=p.extract();for(l=0,A=i.length;l<A;l++){j=i[l];q=v[l];if("auto"===q.value||"auto"===j.value)throw Error("cannot animate "+m+" from or to `auto`");q.unit&&j.unit&&(g=!0,"px"!==q.unit&&(j.value/=fa(o,q.unit),j.unit=q.unit))}j=t.toString(!0);
p=p.toString(!0);g&&u.call(o,j);n.setOptions(d).start(j,p)}}return this};a.prototype.start=function(a,c,d,e){var f;f={};f[c]=d;return this.starts(a,f,e)};a.prototype.sets=function(a,c){var d,e,f,g,h,i,k,l;for(e in c){g=c[e];f=W(e=L(e));for(i=0,h=a.length;i<h;i++){d=a[i];if(null!=(k=this.animations[d["\u00b5id"]]))null!=(l=k[e])&&l.stop(!0);f.call(d,g)}}return this};a.prototype.set=function(a,c,d){var e;e={};e[c]=d;return this.sets(a,e)};return a}());k.prototype.animate=function(a,b,c){"string"!==
typeof a?K.starts(this.valueOf(),a,b):K.start(this.valueOf(),a,b,c);return this};k.prototype.style=function(a,b){"string"!==typeof a?K.sets(this.valueOf(),a):K.set(this.valueOf(),a,b);return this};k.prototype.compute=function(a){return z(L(a)).call(this.valueOf()[0])};"undefined"!==typeof module?module.exports=k:window.moofx=k})();
